services:
  - type: web
    name: toxic-content-detector
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app/main.py"
    envVars:
      - key: API_KEY
        value: your-secret-api-key
